### ISSUE TITLE
Raster jank when displaying many svgs even if wrap ScalableImageWidget with RepaintBoundary and set isComplex to `true`

### ISSUE THREAD

**Issue by zhuscat** [zathras/jovial_svg#108]
I have tried wrapping `ScalableImageWidget` with `RepaintBoundary` and setting `isComplex` to `true`, but I still encounter raster jank. The raster thread takes longer than 16ms per frame. Is there any way I can improve this performance issue? Or is it a problem with the library or a Flutter issue?

## Reproduction

https://github.com/zhuscat/svg_test

## Video

tested on release mode

https://github.com/user-attachments/assets/5db18e3e-9dea-48be-8116-f547bc42312d

## Env

```bash
$ flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.0 23A344 darwin-arm64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.92.0)
[✓] Connected device (4 available)
```

**Comment by zathras** [comment]
Short of me debugging your application, there's no way for me to know.  I'm sure there's some way you could improve your app's performance, but it's not really my place to figure that out for you.  Try making changes so that it doesn't need to re-render the complex SVG during animation.
