### ISSUE TITLE
 Bad state: Attempt to unprepare() an image that was not prepare()d

### ISSUE THREAD

**Issue by jimmyff** [zathras/jovial_svg#110]
I have a `SliverList.builder` that's including `ScalableImageWidget` and I keep getting these errors:
```
════════ Exception caught by widgets library ═══════════════════════════════════
Bad state: Attempt to unprepare() an image that was not prepare()d
════════════════════════════════════════════════════════════════════════════════
```

When I resume the debugger, I can't see any visual issue, am I doing something wrong? If not can I surrpress these? 

Thanks

**Comment by jimmyff** [comment]
actually I might have just fixed the issue by providing a key! 😅 will reopen if need...

**Comment by jimmyff** [comment]
So the keys have improved it, but I do keep occasionally getting this error.  Any pointers on how to avoid it would be great.

Thanks

**Comment by zathras** [comment]
Can you reproduce the problem with a small, stand-alone program?

**Comment by zathras** [comment]
I'd need program to reproduce the issue in order to diagnose this, and determine whether or not it's a bug.
