### ISSUE TITLE
Unsupport for style element inside <svg>

### ISSUE THREAD

**Issue by nal-khangpt** [zathras/jovial_svg#16]
- I wonder that your library can support for this kind of style inside <svg> tag:

```
<style type="text/css">
.st0{fill:#FFFFFF;}
.st1{fill:none;stroke:#000000;stroke-width:0.4473;stroke-miterlimit:10;}
</style>
```

- I got an content of SVG file with style element (like upper), maybe it was exported from: 
`<!-- Generator: Adobe Illustrator 25.2.3, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->`

- For now, I got an exception when my widget loaded with kind of this svg format

**Comment by zathras** [comment]
The way Tiny SVG works for that sort of thing is to put the style information inside an SVG tag, e.g.:
```
<g style="fill: #ffffff;stroke-width:0.4473;  etc.">
    ... SVG elements that use that style ...
</g>
```

The style tags you cite are part of CSS, which are explicitly not a part of SVG Tiny 1.2, and not supported by `jovial_svg`.  Implementing full CSS support would be a substantial undertaking.  Perhaps there's an SVG pre-processor that applies the CSS styles to the SVG, resulting in a "pure" SVG file?

**Comment by zathras** [comment]
Hi @nal-khangpt ,

I was thinking about this one, and adding in-line style elements like this might be a reasonable thing to do.  One thing I'd need is a couple of realistic SVG images that use this tag.  At a minimum, that lets me confirm that I'm implementing enough of that idiom to actually be useful.

If you'd care to share a couple of SVG images I can use for testing, I'll take a look, and if it looks like a reasonable addition to the library, I'll re-open the issue.

Cheers,

Bill
