### ISSUE TITLE
[Question] possible to interact with displayed SVG?

### ISSUE THREAD

**Issue by Nezzquikk** [zathras/jovial_svg#17]
Hello,

I was looking for a library that can display SVGs and also handle click events when pressing on lets say a polygon or rectangle.
It should also be able to get the context of the clicked elements for instance when the polygon has data-attributes.

Is this possible with this library without the use of custompaint?

Thanks!

**Comment by zathras** [comment]
No.  What you're asking for requires supporting a DOM (document object model), which is currently out of scope for this library.

**Comment by Nezzquikk** [comment]
Thank you very much!
