### ISSUE TITLE
DOM support / interactivity?

### ISSUE THREAD

**Issue by zathras** [zathras/jovial_svg#19]
I have no plans at present to add a DOM, but it occurs to me that it would be fairly straightforward to do so.  I thought it would be worthwhile to capture some thoughts about doing so, in case someone wants to take this on, or if I do in the future.

The xml library used by `jovial_svg` offers an `XmlDocument` API that could be used to programmatically manipulate an SVG document.  `ScalableImage` could pretty easily offer a factory method that takes an `XmlDocument` representing an SVG, in addition to the existing API that parses an XML string.  That would make "rendering" an `XmlDocument` to a `ScalableImage` much faster - probably an order of magnitude faster.

But better would be to add a wrapper around `ScalableImage` that holds the `XmlDocument`, and the last `ScalableImage` produced from that document.  When the client wants to modify the `XmlDocument`, they could call a method when modifications are complete, and "render" the document to the new `ScalableImage` instance.  This new instance could use the existing "dagger" functionality (that enables node sharing within the directed acyclic graph representation of an SI) to share the parts of the graph that weren't modified -- notably Path objects.  I bet in most cases, most of the nodes of the original SI would be shared in this way.  That would save some memory, but perhaps more importantly it would help with things like GPU caching.

Next, callbacks.  For interactivity ("scripting"), you need to be able to attach a callback to a node on the DOM tree.  When an `XmlDocument` is "rendered" to an SI, it wouldn't be too much of a trick to carry a callback function to the corresponding DAG node.  `jovial_svg` has an existing method that calculates the bounding rectangle for any node, with all the necessary coordinate transformations.  That could be used for hit detection to deliver callbacks.  A widget could be put around this new `DOMScalableImage` to deliver events, as appropriate.

Finally, image preparation.  In the (probably rare?) case where the SVG has image tags, image preparation would of course have to be dealt with.  In the (certainly very rare) case where the image were modified, that would even have to be asynchronous.  I can't imagine a DOM manipulation actually modifying an image tag like this, but it's conceptually possible, and a weird edge case that would have to be acknowledged somehow, even if only by declaring such modifications illegal.

**Comment by ivofernandes** [comment]
First congrats on such a great project that you did :)

I noticed some time ago that there are projects that can turn a svg into a flutter canvas path. Like this one
https://www.youtube.com/watch?v=U51GvNzBRSc

I also noticed that the DAG class of this project has a paint into canvas, but would be possible to really make the path extraction?

Path manipulation would make possible a lot of stuff in terms of interactivity

**Comment by zathras** [comment]
@ivofernandes  I don't know what you mean by "path extraction."  Would you care to elaborate?

The kind of interactivity I'm talking about in this issue is along the lines of what can be done by manipulating the parse tree of the XML SVG asset (that is to say, the SVG assets document object model, or DOM).  My expectation is that any SVG assets intended to be animated would be set up to be manipulated in this way, e.g. by providing labels on some key nodes that a program could manipulate.

**Comment by ivofernandes** [comment]
So in the web world we tend to put the svg in the Dom and use css and sometimes javascript to animate.

But in flutter we divide and conquer I guess, the dart ui path class already has stuff like compute metrics to facilitate animation, and this way we can integrate the animation totally into flutter.

And for example, if there is some code in the svg to parse and do the animation, how would be possible to animate reacting to events like in javascript we can do?

Like animate with scroll or with some kind of user interaction. This kind of stuff would be quite easier to do in a path I guess

**Comment by zathras** [comment]
@ivofernandes Well, I guess if, hypothetically, there were a DOM API, and node in the parse tree that contains a path could have a method that returns a copy of the Dart `Path` object.  That might be useful for something.

About code in the SVG -- any code in the SVG would be JavaScript, so doing anything with that would be firmly out of scope.

**Comment by Bindslev** [comment]
@zathras Thanks for providing such a high performance and easy to use library for SVG rendering.
I would very much appreciate a functionality like this. Simply being able to register which elements the user clicks on would bring this library to another level, as it could be used for floor planning, maps etc. I have searched the web thin for a library that can render SVG's as nicely as this one, and has interactivity and it's simply not something that exists.
I wish I could help you but I'm simply not experienced enough in flutter, unfortunately.

**Comment by zathras** [comment]
Hi @Bindslev, I wouldn't say it's "in the pipeline" exactly.  Since I wrote the initial description, I've moved to The Philippines (as a Peace Corps volunteer) and moved back to the US, where I'm _almost_ unpacked now.  That said, I might take a look at this in a month or two, especially if it's for a worthy cause.  As a general rule, "someone else is being paid for software and they want me to do stuff for free" isn't all that compelling, whereas "here's a really interesting use case I'm planning to put in a public domain software project that will save orphans" scores pretty highly :-)

I guess "someone else is being paid for software and they will make a donation to the Ukrainian military and show me a receipt" would qualify as a worthy cause too ;-)

**Comment by zathras** [comment]
That's a nice gesture.  I'll take a look at this when I get a chance.  No guarantees, and it'll probably take some time.  At the moment, I'm going through the learning curve of being an executor.  On the one hand, that takes a bunch of time.  On the other, it might be nice to think about something totally different for a while :-)

**Comment by zathras** [comment]
@Bindslev Check out #92 - I have a question for you there.

I'll probably change the title of the current issue (19) to just be "DOM support," and leave it open as a placeholder.

**Comment by zathras** [comment]
Taking another look at this, it's mostly a matter of exposing the SVG parse graph.  For "interactivity," an application could manipulate the parse graph, build a new SI, and display that -- it's a little like "rendering" the parse graph to an SI.  For the DAG representation, large parts of the new SI could be shared with the old one.  Notably, this would include Flutter `Path` objects, so hopefully GPU cache entries would end up getting re-used.

Doing graph manipulations and rebuilding an SI should be at least an order of magnitude faster than changing SVG source and re-parsing, and it's certainly less error prone, and probably easier.  Keeping a parse graph around would obviously have a substantial memory overhead, but then, DOM-like manipulation intrinsically does.

The parse graph isn't the simplest data structure in the world, but after taking a look, I think that this would make a pretty reasonable public API.  An SVG's internal structure just _is_ this complicated!  A bit more refactoring is probably in order, like maybe some strategic name changes, but the basic structure of the parse graph looks pretty sound.  This library has stabilized enough that it's probably OK to expose the parse graph as a public API.

I think it would be fair to not do extensive error checking on invalid uses of the API.  For example, if the app adds a group to its list of children, I think it's fair that the stack would just blow up when they tried to use the resulting invalid graph.  I don't see a real need to detect that, and have a more friendly failure mode.

Here's the parse graph structure, as it stands now:

![svg_parse_graph](https://github.com/zathras/jovial_svg/assets/20762139/fe61e5bf-1b1d-4e3d-ad91-2c783e448fdb)

**Comment by Bindslev** [comment]
Very interesting insights, sure does look a bit complicated! How would this work with preloaded SVG's? I imagine that changing the SVG source and re-parsing could conflict with users that pre-render the SVG before displaying it, or maybe even large SVG's. I personally work with very small SVG's and parsing the SVG is really fast, but I imagine some users may prefer rebuilding the SI if that is also less error prone. 
Would it also be possible to detect the shape itself and only manipulate that? Or would it be restricted to the bounding box of said shape? 
Anyway I'm just brainstorming a bit to help you consider those things :)

**Comment by zathras** [comment]
Hi @Bindslev, check out [1.1.21-rc.3.   ](https://pub.dev/documentation/jovial_svg/1.1.21-rc.3/topics/SVG%20DOM-topic.html).  I'm reasonably happy with how this turned out.  There's also a demo that shows "animating" an SVG using this DOM API (`cd example ; flutter run lib/animation.dart`).

**Comment by Bindslev** [comment]
Hey @zathras, that turned out super nice! Very smooth. Can't wait to combine it with clicking on the elements - the possibilities are endless! Very cool to have this, thanks for putting time into this as well :)

**Comment by zathras** [comment]
Great!

Do you plan to play around with it in the next week or so?  If so, I'll leave the library at RC status.  That gives me freedom to change the API, if you notice something that shouldn't be there, or otherwise needs to be changed.  Once I publish as non-RC, I'll be constrained by needing to maintain backwards compatibility.  There are some other bugs whose publication is on hold, so I don't want to hold off too long.

If you're not planning to do anything soon, that's fine.  Just let me know.  I'm pretty confident in the API as it stands, so I'm OK with publishing now.

**Comment by Bindslev** [comment]
Definitely am!
In fact, I am already playing around with it and I haven't found anything yet. Only thing I noticed, and it might be intentional; on `ScalableImage.fromSvgString`, you can provide a function in the `warnF` parameter, I assume because `warn` is used as a bool. In the `SvgDOMManager.fromString` you have a parameter with similar signature but this time it is called `warn` instead of `warnF`.
Could be because you don't have the `warn` parameter for this function, but in case you hadn't noticed and it wasn't intentional then now you know :)
Other than that, really enjoying playing around with it so far, I'll report back here within the weekend if I have other findings!

**Comment by Bindslev** [comment]
Another observation that I made, which may not be possible but would be awesome!
Say I am creating my SI like this:

`si = ScalableImage.fromSvgString(mapSvg, exportedIDs: [RegExp('(room_).*')])`

And when the user clicks a room, I will paint it as if it's "toggled" or "chosen" because that looks cool! But, then I will have to build the SI again, like in your demo:

`si = svgDom.build();`

However, it seems that the previously declared `exportedIDs` are now lost, since I rebuilt the SI and override the `si`, so I can't find any exportedID's on the second click if that makes sense.

Is there a way to rebuild the SI with the exportedID's that I don't know about or is this even possible? :)

**Comment by zathras** [comment]
I changed `warn` to `warnF` - consistency is better here.

You should just be able to call `si.exportedIDs` on the new SI instance to get the new, updated `Set`.  I added some documentation about this, and added click detection to the `animation.dart` example.

**Comment by Bindslev** [comment]
> You should just be able to call `si.exportedIDs` on the new SI instance to get the new, updated `Set`. I added some documentation about this, and added click detection to the `animation.dart` example.

Ahh right! I got it now, thanks for updating the animation example. It works perfectly! Above all my expectations :) Not only can I detect where on the SVG I'm clicking, I can also make it visible now with these interactions - it's so neat. 

I think it would be great update the package description on pub.dev when you have released this officially, since I have stumbled upon many people wanting exactly what you have now made here.

I have another idea for something awesome that I have seen people need that seems to not exist, should I make an issue on that? I don't need it myself, nor might it be in scope but in case it is and you think it would be interesting to look into, then I know there's at least some demand out there :)

**Comment by zathras** [comment]
Sure, ideas are welcome.  Even it turns out to be something unduly hard or without sufficient known demand, it's still good to have an open enhancement in the issues database, as a collecting point and a sort of "explicit non-feature" list.

**Comment by zathras** [comment]
Released in 1.1.21
