### ISSUE TITLE
Certain SVGs won't load

### ISSUE THREAD

**Issue by jimmyff** [zathras/jovial_svg#28]
Hi, firstly thanks very much for this awesome package. I'm having a lot of success with it but I keep coming across certain SVGs that won't load. My process to try and get SVGs working is: 

1. Import to Inkscape 
2. Document properties -> Resize to content
3. Export as 'Optimised SVG'. 

Example of Svg that won't load:

![xmas_stocking](https://user-images.githubusercontent.com/298850/202304940-29a5f11f-d651-411b-aa7e-1d1975426d48.svg)

Any ideas?

Thanks

**Comment by zathras** [comment]
That one worked for me.  Maybe a different image doesn't work?
![Screen Shot 2022-11-16 at 4 50 08 PM](https://user-images.githubusercontent.com/20762139/202326977-ab8b1d10-b558-4a94-823f-acfb5942fdea.png)

**Comment by zathras** [comment]
I haven't heard back.  In the absence of a way of reproducing the problem, there's not much I can do.  Maybe it was a problem in your app that you've since fixed?  Feel free to re-open if you can come up with an SVG that doesn't work with this library.
