### ISSUE TITLE
Explicitly ignore data-* attributes without warning

### ISSUE THREAD

**Issue by IchordeDionysos** [zathras/jovial_svg#30]
When parsing SVGs the parser will flag `data-*`-attributes as unknown properties.

e.g. an SVG like this:
```svg
<svg data-name="Ebene 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 633.1 221"></svg>
```

will throw this warning:
```
    Ignoring data-name attribute(s) in svg
```

However, the `data-*`-attributes are [known non-UI related attributes](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/data-*) and there has no effect, throwing an error will result in noise in the warnings.

This issue can be considered as a request to support `data-*`-attributes in the sense of simply ignoring them similar to how its done for [`xmlns`](https://github.com/zathras/jovial_svg/blob/aef9abfb6853b8de3a42f466387d43cef73472c6/lib/src/svg_parser.dart#L213)

**Comment by zathras** [comment]
Published as 1.1.9
