### ISSUE TITLE
Can't change the color of a SVG

### ISSUE THREAD

**Issue by RahmiTufanoglu** [zathras/jovial_svg#38]
I try to change the color of svg icons with the currentColor property. But it does not overwrite the black color.

```
static late final ScalableImage _mySvg1;
static ScalableImage get mySvg1 => _mySvg1;

static Future<void> loadSvgs() async {
  _mySvg1 = await ScalableImage.fromSvgAsset(
    rootBundle,
    GlobalAssets.icon1,
    currentColor: Colors.red,
  );
}

SizedBox(
    height: 32,
    child: ScalableImageWidget(si: GlobalAssets.mySvg1),
),
```

**Comment by zathras** [comment]
Are you sure the SVG asset uses current color properly?  Do you have a small (like, 10 or 20 line) SVG that can be used to reproduce the issue?

**Comment by RahmiTufanoglu** [comment]
> Are you sure the SVG asset uses current color properly? Do you have a small (like, 10 or 20 line) SVG that can be used to reproduce the issue?

Sure here:
```
<svg width="150" height="150" viewBox="0 0 150 150" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M18 30H75H132M18 75H132ZM18 120H132Z" fill="#878787"/>
<path d="M18 30H75H132M18 75H132M18 120H132" stroke="#AAAAAA" stroke-width="15" stroke-linecap="round" stroke-linejoin="round"/>
</svg>

```

**Comment by RahmiTufanoglu** [comment]
> 

Now I understand. Thanks. But can I change the color here, or do I have to preload the SVG with the different color everytime?
```
SizedBox(
    height: 32,
    child: ScalableImageWidget(si: GlobalAssets.mySvg1),
),
```

**Comment by zathras** [comment]
No; see https://pub.dev/documentation/jovial_svg/latest/jovial_svg/ScalableImage/modifyCurrentColor.html

**Comment by RahmiTufanoglu** [comment]
The following code does not change the color

```
  activeIcon: SizedBox(
              height: 32,
              child: ScalableImageWidget(
                si: GlobalAssets. mySvg1.modifyCurrentColor(MyColors.amber),
              ),
            ),
```

**Comment by Mage111** [comment]
> Your SVG isn't setting anything to "currentColor". The default color in SVG is black.
> 
> A quick Duckduckgo search turned up this tutorial; at a brief glance it seems to get it right: https://gomakethings.com/currentcolor-and-svgs/

what is actually "currentColor" in SVG? do you mean the path "fill" property?
