### ISSUE TITLE
currentColor has no affect on SVG

### ISSUE THREAD

**Issue by alfietapping** [zathras/jovial_svg#41]
Using the below code to fetch an svg from my assets folder and attempting to change the svg's color, however using `currentColor` doesn't do anything and the svg remains the same color

```
Future<void> setImage() async {
    ScalableImage svg =
    await ScalableImage.fromSvgAsset(rootBundle, 'assets/images/9.svg', currentColor: Colors.blue);
    setState(() {
      image = svg;
    });
  }
```

**Comment by zathras** [comment]
Does the SVG actually use currentColor?  Have you compared your code and your SVG with `example/lib/current_color.dart`? 

If you think there's a problem with the library, I would of course need a copy of an SVG asset that reproduces the problem.

**Comment by zathras** [comment]
Non-responsive submitter.  It was probably the SVG.
