### ISSUE TITLE
A big problem  with  double svg balis

### ISSUE THREAD

**Issue by mimoislam** [zathras/jovial_svg#43]
I/flutter (23580):     Ignoring preserveaspectratio attribute(s) in svg
I/flutter (23580): ParseError(Second <svg> tag in file)
can you help me please

**Comment by zathras** [comment]
Well, that depends.  If you can provide an example of an SVG file that's reasonably simple, that you've looked at, and that you're confident should work, perhaps.  It would help if you did a bit of testing, to make sure you know where exactly it's failing, and to verify that it is, in fact, a valid SVG.

You have to be willing to do a bit of work on your end to narrow it down.  Saying "something isn't working, I don't know why, and I didn't take the time to provide essential context" isn't a winning strategy.

**Comment by zathras** [comment]
Submitter non-responsive.

**Comment by mimoislam** [comment]
I am sorry but i wan't here for the past day my problem is with svg file inside it there is two diffrent svg balise . here is an example https://svgshare.com/i/q6J.svg . i couldn't find any package that works  . and one of the best packages are you so i wanted to submit this error if you can help . i am sorry for not responding any soon .

**Comment by zathras** [comment]
OK.  Did you look at the SVG file?  It has an <svg> tag inside a group.  That's **definitely** not supported.

Look at the limitations discussed in the project `README` - it spends a page or two discussing what is and isn't supported.  Pay particular attention to "Supported SVG Profile" and "Goals and Package Evolution."

Also, check your assets with a validator, to see if it's even valid SVG.  See, for example, https://validator.w3.org/check?uri=https%3A%2F%2Fsvgshare.com%2Fi%2Fq6J.svg&charset=%28detect+automatically%29&doctype=Inline&group=0
