### ISSUE TITLE
`ScalableImageSource.fromSvgHttpUrl` is not cached between `Route`s even if `cache` is set

### ISSUE THREAD

**Issue by AlexV525** [zathras/jovial_svg#44]
```dart
return ScalableImageWidget.fromSISource(
  si: ScalableImageSource.fromSvgHttpUrl(_imageUri),
  fit: BoxFit.cover,
  cache: ScalableImageCache(size: 15),
);
```

Wrapping the above code into `Hero`s doesn't look like `Image` that can use the painting caches, so images are flashing between heroes.

https://user-images.githubusercontent.com/15884415/218246729-1abc5859-f14a-47c4-870e-0f5935449bf6.mp4

**Comment by zathras** [comment]
Well, yeah.  You're creating a new cache each time.  Look at `example/lib/cache.dart`.

**Comment by AlexV525** [comment]
Sorry and thanks for the kind help!
