### ISSUE TITLE
Failed to parse SVG

### ISSUE THREAD

**Issue by AlexV525** [zathras/jovial_svg#47]
Source: https://sr4qi-vaaaa-aaaah-qcaaq-cai.raw.ic0.app/?tokenid=qnnxg-iikor-uwiaa-aaaaa-b4aqa-eaqca-aaaaa-q

The display is completely empty.

![](https://sr4qi-vaaaa-aaaah-qcaaq-cai.raw.ic0.app/?tokenid=qnnxg-iikor-uwiaa-aaaaa-b4aqa-eaqca-aaaaa-q)

**Comment by zathras** [comment]
If you think there's a bug, please explain why you think it *should* have worked, and include a reasonably small asset that reproduces the problem.  But first, be sure to read the README about what is and isn't supported.
