### ISSUE TITLE
Use Dart as a serialization format

### ISSUE THREAD

**Issue by csells** [zathras/jovial_svg#5]
I assume that the way this package works is that SVG is translated into Flutter widgets at run-time. In that case, it would be useful to have a CLI version of this package that reads the SVG and generates the Flutter code ahead of time. That would enable a static SVG asset to be compiled into a Flutter app w/o the need to read a .svg or .si file at run-time at all.

**Comment by zathras** [comment]
Well...

No, it does not translate an SVG into flutter widgets at runtime.  Doing that would actually be quite inefficient, especially in terms of memory footprint.  It works by drawing to a Canvas object.

Translating into other representations, up to and including generating dart code that draws to a canvas would of course be possible, but it's unlikely this would be faster in any important way.  With the .si format, it's already the case that execution time is dominated by the rendering operations in any reasonable execution scenario I can think of.  That sort of think isn't out of the question, but a compelling use scenario backed by real performance data would be a good first step toward justifying the added complexity.

**Comment by csells** [comment]
understood. thanks!
