### ISSUE TITLE
Isolation support?

### ISSUE THREAD

**Issue by IchordeDionysos** [zathras/jovial_svg#50]
Is `isolation: isolate` a supported attribute?

I've seen it being used [in one of the demo files,](https://github.com/zathras/jovial_svg/blob/07956df86935835c600ceee192de5ba40668af9b/demo/assets/svg/stylesheet.svg?short_path=9fdd443#L10) but when we use it, it leads to a warning being thrown...

The way we have set up our upload process leads to an error (`Ignoring isolation attribute(s) in g`) being thrown when an unsupported SVG feature is detected to make sure only SVG files are uploaded that are properly supported.

**Comment by zathras** [comment]
No, it's not.  In the referenced file, it's a CSS attribute, and unrecognized CSS attributes are ignored - it doesn't throw an error, nor does it generate a warning.
