### ISSUE TITLE
<pattern /> element seems to be ignored 

### ISSUE THREAD

**Issue by vladchuk** [zathras/jovial_svg#58]
This is part of the SVG 1.1 specs, described here: https://www.w3.org/TR/SVG11/pservers.html#PatternElement.
Yes it seems to be ignored (mishandled?) by jovial_svg: the example in the specification above is rendered with outlines (rectangle and ellipse) only, no pattern. It is correctly rendered by mainstream tools (browsers, IDEs, etc.).

Please add support for it or else document it as not supported. Thanks!

**Comment by vladchuk** [comment]
I looked through the code, and it seems that patterns are deliberately ignored, but I didn't find anything in the jovial documentation. Did I miss it? So, it's not a bug, after all. Should I bother with a feature request or is this as good as it gets?

Please advise.

**Comment by zathras** [comment]
"Deliberately ignored" is a stretch, but it's probably not implemented.  I actually just moved to a different country; I'll take a look when I am a little more settled.  I'll have to take a look as to whether or not it fits in with the intended scope of the library.

**Comment by billf-pshs** [comment]
OK, patterns are an "interesting" feature of SVG (one might be tempted to say "gold plating").  To implement this, I guess the pattern would have to be rendered , masked by the containing shape.  I guess it's doable, but it's a fair amount of implementation complexity.  It's not out of the question, but this does seem like a relatively obscure, infrequently used feature.  For now I'm just updating the README to say it's not supported.  I think I'll leave it at that, and not spin a new release just for a one-line informative README note.

**Comment by vladchuk** [comment]
Hello Bill, good to hear from you again. As usual, thank you for looking into this and updating the docs.
I have another issue I wanted to bring up with you, but I'm not sure what's the best way/place. It's more of a question/discussion, not an issue (at least at this point). What would you suggest?
