### ISSUE TITLE
I can not to update http library in latest version 1.0.0 

### ISSUE THREAD

**Issue by emanuelzallikodelabs** [zathras/jovial_svg#59]
Can’t update htpp library in the latest version 1.0.0 because jovial_svg 1.1.14 depends on http ^0.13.6

Flutter 3.10.1 • channel stable • https://github.com/flutter/flutter.git
Tools • Dart 3.0.1 • DevTools 2.23.1

**Comment by zathras** [comment]
pubspec versions updated.
