### ISSUE TITLE
add name as optional param for loaded assets.

### ISSUE THREAD

**Issue by DarkHeros09** [zathras/jovial_svg#63]
Hello,

I would like to express my gratitude for creating and continuously updating this outstanding package.

As my Flutter project grows in size and requires a large number of images to load, it would be convenient to access my assets by their names. For example:
```dart
ScalableImage.fromSIAsset(rootBundle, 'assets/logo.si', 'logo');
ScalableImage.fromSIAsset(rootBundle, 'assets/icon.si', 'icon');
```

By doing so, I can easily add them to a list and iterate through them by name.

Thank you.

**Comment by zathras** [comment]
I don't understand...  Why don't you just put them on a map that you maintain in your app, like this?
```
final myAssets = {
    'logo' : ScalableImage.fromSIAsset(rootBundle, 'assets/logo.si', 'logo'),
    'whateverNameIWant' : ScalableImage.fromSIAsset(rootBundle, 'assets/icon.si', 'icon'),
}```

**Comment by DarkHeros09** [comment]
> I don't understand...  Why don't you just put them on a map that you maintain in your app, like this?
> ```
> final myAssets = {
>     'logo' : ScalableImage.fromSIAsset(rootBundle, 'assets/logo.si', 'logo'),
>     'whateverNameIWant' : ScalableImage.fromSIAsset(rootBundle, 'assets/icon.si', 'icon'),
> }```

Yes, you are absolutely correct.

Thank you.
