### ISSUE TITLE
Converted si files color

### ISSUE THREAD

**Issue by DarkHeros09** [zathras/jovial_svg#64]
Is it possible for (SI) files converted from SVG to support coloring? I ask because I'm utilizing the "currentColor" property, but it doesn't seem to be functioning properly.

When I use the SVG variant, the coloring works as expected.

The conversion used by the cli.

**Comment by DarkHeros09** [comment]
Any update on this?

**Comment by billf-pshs** [comment]
Compiling an SVG file to a .si should work, and should equally support currentColor.

Please attach code and assets to reproduce the problem, like:

- An SVG that works as expected
- A conversion to .si that doesn't work
- A small stand-along program that demonstrates the problem

**Comment by DarkHeros09** [comment]
Hi


asset
![home](https://github.com/zathras/jovial_svg/assets/39935182/8cf612d1-069c-46dc-aaec-bf783c0c9acb)

main.dart
```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:jovial_svg/jovial_svg.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  final homeIcon = await ScalableImage.fromSIAsset(
    rootBundle,
    "assets/home.si",
    currentColor: Colors.red,
  );
  runApp(MyApp(
    homeIcon: homeIcon,
  ));
}

class MyApp extends StatelessWidget {
  const MyApp({super.key, required this.homeIcon});

  final ScalableImage homeIcon;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
          colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
          useMaterial3: true,
        ),
        home: Scaffold(
          body: Center(
            child: ScalableImageWidget(si: homeIcon),
          ),
        ));
  }
}
```

pubspec.yaml
```yaml
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  jovial_svg: ^1.1.15

  assets:
    - assets/
  ```
  
  The svg file needs to be converted to si format, as i couldn't upload it because the format is not supported on github.
  
  Thank you.

**Comment by zathras** [comment]
You can attach SVG files to a github issue by putting it inside a zip file - see attached.file:///home/billf/tmp/tmp/foo.zip

**Comment by zathras** [comment]
The SVG file you attached doesn't use SVG's currentColor feature.  When you use the original SVG versus the SI in the program you attached, is there any rendering difference?  If you change currentColor from red to say, green, what changes in the rendering of the original SVG?  Anything?

**Comment by DarkHeros09** [comment]
> The SVG file you attached doesn't use SVG's currentColor feature. When you use the original SVG versus the SI in the program you attached, is there any rendering difference? If you change currentColor from red to say, green, what changes in the rendering of the original SVG? Anything?

You are accurate. The issue lay with the svg file. After adding the currentColor property to the svg file and converting it to "si," the problem was resolved.

thank you for having time and patience to answer my question.
