### ISSUE TITLE
Can you add color, It is hard to change color variable in svg when You have 30 files

### ISSUE THREAD

**Issue by Hellomik2002** [zathras/jovial_svg#73]

**Comment by zathras** [comment]
I don't understand what you're asking for.

**Comment by Hellomik2002** [comment]
in flutter svg you can set the color and the whole svg will be that color, but in jovial svg I need to change SVG file and set currentColor to all colors

**Comment by Hellomik2002** [comment]
At the current moment I do that, but It will be better if package will have this feature as flutter svg 

```RegExp colorRegex = RegExp(
    r'(?:#|0x)([a-fA-F0-9]{3}|[a-fA-F0-9]{6})\b|(?:rgb|hsl)a?\([^\)]*\)',
    caseSensitive: false);
    
     svgLocal =
          svgLocal.replaceAllMapped(colorRegex, (match) => "currentColor");```

**Comment by zathras** [comment]
Setting `currentColor` is already supported.  See, for example, `ScalableImage.modifyCurrentColor`.

Note that there is a bug if the SVG has a transformation -- #71

**Comment by Hellomik2002** [comment]
That case won't work when You have this svg 
```
<svg version="1.1" width="50" height="50" xmlns="http://www.w3.org/2000/svg">
      <g fill="red" transform="translate(1 1)">
        <circle cx="25" cy="25" r="20" />
      </g>
    </svg>
 ```

**Comment by zathras** [comment]
Correct.  So are you asking for support for currentColor, as per your first comment, or for a general ability to edit colors throughout the structure of an arbitrary SVG, as per your second comment?  Or are you asking for something else?

Please be specific, and provide enough detail and a complete description of what you're asking for.

**Comment by Hellomik2002** [comment]
I am asking general ability to edit colors throughout the structure of an arbitrary SVG, 
For example  I have SVG like that
```
<svg version="1.1" width="50" height="50" xmlns="http://www.w3.org/2000/svg">
      <g fill="red" transform="translate(1 1)">
        <circle cx="25" cy="25" r="20" />
      </g>
    </svg>
```
But when use it like that 
```
ScalableImageWidget.fromSISource(
          si: ScalableImageSource.fromSvg(
            rootBundle,
            assetPath,
            color: Colors.orange,
          ),
          fit: BoxFit.cover,
          reload: false,
        )
```
My circle should be orange

**Comment by zathras** [comment]
OK, that's covered under #19.  I have no plans to add that kind of extension at this time, but if there's a compelling enough reason, I'm open to considering it.

If you're just interested in editing static SVG files, I'm sure you'll find many ways of doing that off-line, though.
