### ISSUE TITLE
 stroke-dashoffset not applied correctly

### ISSUE THREAD

**Issue by dubsky** [zathras/jovial_svg#76]
When  stroke-dashoffset is specified, it is applied to all dashing segments, instead of applying it only to the contour start. This results in strange behavior when dash offset is actually ruining stroke-dasharray configuration.

**Comment by billf-pshs** [comment]
OK.  You don't need permission to make a pull request AFAIK -- You just make it, and I get a notification.

Do you have an SVG asset that clearly shows the problem?  That would be very helpful, and would be useful for a regression test.  Usually with these things, getting a sample asset that clearly shows the feature and tests the desired behavior is about 80% of the work.

**Comment by zathras** [comment]
Is the change to lib/src/common.dart from https://github.com/zathras/jovial_svg/commit/a0d95b336bc9cd5e5bc9c46738f41e6d9f866062 the same as your fix?

**Comment by dubsky** [comment]
Sorry, I am not that fast. Anyway, I wouldn't create the tests, etc...

What I did involved a little more additional code, but I tested your fix (including more than 2 segments in the dash array) and it works nicely. 

Thanks.
