### ISSUE TITLE
 currentColor property not affects the SVG

### ISSUE THREAD

**Issue by Mage111** [zathras/jovial_svg#83]
jovial_svg: ^1.1.19
Dart SDK version: 3.2.0 (stable)
flutter: 3.16.0

The code:
```
`     return  ScalableImageWidget.fromSISource(
            currentColor: Colors.red,
            fit: BoxFit.fill,
            si: ScalableImageSource.fromSvgHttpUrl(
                Uri.parse(path)));`
```

There is an issue with the 'currentColor' property, despite being defined as red, it remains black, as specified in its SVG file

the SVG file content:
```
<svg xmlns="http://www.w3.org/2000/svg" width="41" height="41" viewBox="0 0 41 41" fill="none">
  <path d="M20.9311 34.5352C18.9262 34.5352 17.0411 34.1547 15.2756 33.3939C13.51 32.633 11.9743 31.6004 10.6683 30.296C9.36231 28.9917 8.32841 27.4579 7.56658 25.6946C6.80474 23.9313 6.42383 22.0472 6.42383 20.0424C6.42383 18.0376 6.80426 16.1524 7.56512 14.3869C8.32601 12.6214 9.35862 11.0856 10.663 9.77966C11.9673 8.47366 13.5011 7.43974 15.2644 6.67791C17.0277 5.91607 18.9117 5.53516 20.9166 5.53516C22.9214 5.53516 24.8066 5.91559 26.5721 6.67645C28.3376 7.43734 29.8734 8.46995 31.1793 9.77428C32.4853 11.0786 33.5192 12.6125 34.2811 14.3757C35.0429 16.139 35.4238 18.0231 35.4238 20.0279C35.4238 22.0327 35.0434 23.9179 34.2825 25.6834C33.5216 27.4489 32.489 28.9847 31.1847 30.2907C29.8803 31.5967 28.3465 32.6306 26.5832 33.3924C24.82 34.1542 22.9359 34.5352 20.9311 34.5352ZM20.9238 33.3685C24.6461 33.3685 27.7988 32.0768 30.3822 29.4935C32.9655 26.9102 34.2572 23.7574 34.2572 20.0352C34.2572 16.3129 32.9655 13.1602 30.3822 10.5768C27.7988 7.99349 24.6461 6.70182 20.9238 6.70182C17.2016 6.70182 14.0488 7.99349 11.4655 10.5768C8.88216 13.1602 7.59049 16.3129 7.59049 20.0352C7.59049 23.7574 8.88216 26.9102 11.4655 29.4935C14.0488 32.0768 17.2016 33.3685 20.9238 33.3685Z" fill="black"/>
</svg>
```

**Comment by zathras** [comment]
The SVG asset doesn't use `currentColor`.

**Comment by Mage111** [comment]
so there is no way to change the color? (like flutter_svg)?

**Comment by zathras** [comment]
> so there is no way to change the color? (like flutter_svg)?

If the asset uses `currentColor`, you can set that value.  AFAIK this is exactly what `flutter_svg` provides, but if you could tell me more specifically what you mean, I might be able to explain.  Maybe a code sample of what you're doing with `flutter_svg`?

**Comment by Mage111** [comment]
this is the code that doing with flutter_svg:
` return SvgPicture.network(
          path,
          width: 500,
          height: 500,
          colorFilter: ColorFilter.mode(Colors.red, BlendMode.srcIn),
        );`
and this is the RED result:
![image](https://github.com/zathras/jovial_svg/assets/23486790/daac8efc-eb07-4768-9ba3-79286ab393ad)

**Comment by zathras** [comment]
Well, a Flutter `ColorFilter` has nothing to do with an SVG's `currentColor` property.

Is there a reason you're not just wrapping Flutter's `ColorFiltered` widget around the widget displaying the SVG?

**Comment by Mage111** [comment]
It works!
thanks for the idea! 
I'm quite new to Flutter
