### ISSUE TITLE
Unnecessary url_launcher plugin

### ISSUE THREAD

**Issue by cheymos** [zathras/jovial_svg#86]
After adding the package to my project I found that it [pulls the url_launcher plugin](https://github.com/zathras/jovial_svg/blob/main/pubspec.yaml#L33C1-L33C1), but it is not used anywhere.
I suggest removing it from dependencies.
Thanks!

**Comment by cheymos** [comment]
Implemented this in #87

**Comment by zathras** [comment]
Published as 1.1.20-rc.1.  Let me know if you want it published as 1.1.20 soon; if not, I might leave it as an rc for a bit.

**Comment by cheymos** [comment]
> Published as 1.1.20-rc.1. Let me know if you want it published as 1.1.20 soon; if not, I might leave it as an rc for a bit.

Maybe let's publish it? Thanks!
