### ISSUE TITLE
Use ScalableImageWidget with file

### ISSUE THREAD

**Issue by felixkwok2** [zathras/jovial_svg#88]
Hello,

I see that there are:
 - "fromSvgHttpUrl" which load from url
 - "fromAvd" which load from asset bundle
 - "fromSvg" which also load from asset bundle

I would like to ask if there is any way to use ScalableImageWidget with a File object? (maybe download from some remote source via the app, so it is not in the asset bundle)

Looking for:

```
File file = File(localFilePath);

return ScalableImageWidget.fromSISource(
  si: ScalableImageSource.fromFile(file),
);
```

Thank you.

**Comment by zathras** [comment]
Released in 1.1.21
