### ISSUE TITLE
Explore the ability to render `pixelated` SVG

### ISSUE THREAD

**Issue by AlexV525** [zathras/jovial_svg#89]
**Before Submitting**

*I understand the goal of the package is to provide a robust ability of SVG support, which means the feature request might not be in the scope of the package, it's a CSS standard for images.*

`pixelated` is a property of `image-rendering` in CSS. https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering
The definition:
> The image is scaled with the "nearest neighbor" or similar algorithm, preserving a "pixelated" look as the image changes in size.

This is a super useful feature for static images. Our use case is to deal with NFTs, which include various small, pixelated SVGs.

### Comparison

| Non-pixelated | Pixelated |
|----|----|
| ![image](https://github.com/zathras/jovial_svg/assets/15884415/5ddfd3fe-c0c5-4505-9900-0fa02d76e215) | ![image](https://github.com/zathras/jovial_svg/assets/15884415/8cea33e1-f405-4f6a-aa1f-73cc02535f9a) |

**Comment by zathras** [comment]
This sounds like something best done outside an SVG library.  Unless I'm missing something, it's a transformation done on any rendered image; the fact that the source is SVG isn't all that relevant.  

A quick Duckduckgo search turns up https://pub.dev/documentation/image/latest/image/pixelate.html .  You should be able to render an SVG into an Image, and then use this API.
