### ISSUE TITLE
Get SVG string from ScalableImage

### ISSUE THREAD

**Issue by paurakhsharma** [zathras/jovial_svg#90]
I would like to get some information from the SVG. Mainly `fill` color similar to `currentColor` to make the background color of the screen dynamic.

I have [this SVG](https://firebasestorage.googleapis.com/v0/b/theword121app.appspot.com/o/map.svg?alt=media&token=ccbdb435-e8de-49c1-9878-e18337d826bf) from it I am planning to return the top level `fill` color.

So, I am planning to write my own Regex parser to get this color. Something like this:

```dart
import 'package:flutter/widgets.dart';

Color? imageBackgroundColor(String svg) {
  final lines = svg.split('\n');
  if (lines.length < 2) return null;
  final regex = RegExp(r'^<rect.+fill="#([0-9A-Fa-f]{6})"');
  final match = regex.firstMatch(lines[1]);
  if (match == null) return null;

  return HexColor.fromHex(match.group(1)!);
}

extension HexColor on Color {
  /// String is in the format "aabbcc" or "ffaabbcc" with an optional leading "#".
  static Color fromHex(String hexString) {
    final buffer = StringBuffer();
    if (hexString.length == 6 || hexString.length == 7) buffer.write('ff');
    buffer.write(hexString.replaceFirst('#', ''));
    return Color(int.parse(buffer.toString(), radix: 16));
  }
}
```

But I am unable to do so because `ScalableImage` doesn't have a method to get the string out of it.
i.e there is no `ScalableImage.toSvgString()`

Can you please add this method for `ScalableImage` (either `.toSvgString()` or `.fill`) else my option would be to fetch the network image separately and get the color that way, but I would prefer to not call the SVG url twice.

Thanks in advance.

**Comment by zathras** [comment]
`ScalableImage` doesn't maintain a copy of the source string, but you could just fetch the image into a string once, and then build the ScalableImage from that using the appropriate factory method.

**Comment by paurakhsharma** [comment]
Thank you for the response, I see fetching the SVG string manually and then using `ScalableImage.fromSvgString` does the trick.
