### ISSUE TITLE
Support lists as font-family attribute

### ISSUE THREAD

**Issue by edhom** [zathras/jovial_svg#91]
The [font-family attribute](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/font-family) in the SVG standard is a prioritized list of font family names and/or generic family names. When exporting svgs with referenced text, sometimes fallback fonts are added, which breaks Jovial.
E.g. given that the font `NexaRegularItalic` and the font `Nexa` are listet as fonts in `pubspec.yaml`, `font-family="NexaRegularItalic, Nexa"` in an SVG will not use Nexa but the default font instead.

**Comment by zathras** [comment]
> ... will not use Nexa but the default font instead.

Not surprising, but it might not be too hard to add more extensive support for text fonts in this way.

Please provide an asset that can be used to reproduce the issue.  I just make it a policy to always ask the submitter for that; it removes a source of ambiguity, which can be important with a gigantic hodgepodge like the W3C SVG specifications.

**Comment by edhom** [comment]
Sure, [here](https://github.com/zathras/jovial_svg/assets/47747733/da198b3b-d3ed-42aa-b841-5d02530dea4c) it is!

**Comment by edhom** [comment]
@zathras That was fast, thank you:)

**Comment by zathras** [comment]
Released in 1.1.21
