### ISSUE TITLE
 CSS Attribute and Id selection do not work

### ISSUE THREAD

**Issue by Matthew-w56** [zathras/jovial_svg#93]
**Summary**

I am trying to add in some CSS to an svg to highlight a specific element with a given ID.  I haven't seen anything that says that ID selection is outside of scope for this (amazing) library.

**Describe the bug**

When I render an svg for a piece of sheet music, it renders just fine.  Then I add a style that selects all <g> tags and sets the fill to blue, and that works (all notes draw as blue).  However, it breaks down when I try to say #d1e134 (and there is a g tag with that id).  When I do this, nothing is blue, not even the note I am trying to select.  The same holds even for sanity checks such as [id] (and every element has an id).  Am I unaware of a lack of support for attribute selection with CSS?

**Additional context**

Minimum viable file to reproduce error with:

<svg class="definition-scale" color="black" viewBox="0 0 21000 29700" width="2100px" height="2970px" overflow="visible">
   <defs>
      <symbol id="E0A4-5oknge" viewBox="0 0 1000 1000" overflow="inherit">
         <path transform="scale(1,-1)" d="M0 -39c0 68 73 172 200 172c66 0 114 -37 114 -95c0 -84 -106 -171 -218 -171c-64 0 -96 30 -96 94z" />
      </symbol>
   </defs>
   <style type="text/css">#d1e116 {fill: blue; color: blue;}</style>
    <g id="d1e116" class="note">
	    <g class="notehead">
		    <use xlink:href="#E0A4-5oknge" x="2242" y="3693" height="720px" width="720px" />
	    </g>
	    <g id="a11g7frf" class="accid" />
    </g>
</svg>

Expected result: the note head is blue
Result observed: the note head is black

**Comment by Matthew-w56** [comment]
Sorry, I had filled the rest out I'm not sure where it went. Here it is:

<svg class="definition-scale" color="black" viewBox="0 0 21000 29700" width="2100px" height="2970px" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:mei="http://www.music-encoding.org/ns/mei" overflow="visible">
   <defs>
      <symbol id="E0A4-5oknge" viewBox="0 0 1000 1000" overflow="inherit">
         <path transform="scale(1,-1)" d="M0 -39c0 68 73 172 200 172c66 0 114 -37 114 -95c0 -84 -106 -171 -218 -171c-64 0 -96 30 -96 94z" />
      </symbol>
    </defs>
    <style type="text/css">#d1e116 {fill: blue; color: blue;}</style>
    <g id="d1e116" class="note">
       <g class="notehead">
          <use xlink:href="#E0A4-5oknge" x="2242" y="3693" height="720px" width="720px" />
       </g>
       <g id="a11g7frf" class="accid" />
    </g>
</svg>

**Comment by Matthew-w56** [comment]
'<svg class="definition-scale" color="black" viewBox="0 0 21000 29700" width="2100px" height="2970px" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:mei="http://www.music-encoding.org/ns/mei" overflow="visible">
   <defs>
      <symbol id="E0A4-5oknge" viewBox="0 0 1000 1000" overflow="inherit">
         <path transform="scale(1,-1)" d="M0 -39c0 68 73 172 200 172c66 0 114 -37 114 -95c0 -84 -106 -171 -218 -171c-64 0 -96 30 -96 94z" />
      </symbol>
    </defs>
    <style type="text/css">#d1e116 {fill: blue; color: blue;}</style>
    <g id="d1e116" class="note">
       <g class="notehead">
          <use xlink:href="#E0A4-5oknge" x="2242" y="3693" height="720px" width="720px" />
       </g>
       <g id="a11g7frf" class="accid" />
    </g>
</svg>'

**Comment by Matthew-w56** [comment]
Hm, it keeps removing it

**Comment by Matthew-w56** [comment]
`<svg class="definition-scale" color="black" viewBox="0 0 21000 29700" width="2100px" height="2970px" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:mei="http://www.music-encoding.org/ns/mei" overflow="visible">
   <defs>
      <symbol id="E0A4-5oknge" viewBox="0 0 1000 1000" overflow="inherit">
         <path transform="scale(1,-1)" d="M0 -39c0 68 73 172 200 172c66 0 114 -37 114 -95c0 -84 -106 -171 -218 -171c-64 0 -96 30 -96 94z" />
      </symbol>
    </defs>
    <style type="text/css">#d1e116 {fill: blue; color: blue;}</style>
    <g id="d1e116" class="note">
       <g class="notehead">
          <use xlink:href="#E0A4-5oknge" x="2242" y="3693" height="720px" width="720px" />
       </g>
       <g id="a11g7frf" class="accid" />
    </g>
</svg>`

**Comment by zathras** [comment]
Ah, I see.  CSS has a syntax to specify an individual node, by ID.  Yes, that wasn't implemented, but it's a reasonable thing to add.

**Comment by zathras** [comment]
Note to self:  Here's a massaged asset that reproduces the same thing, and is more visible, and suitable for a regression test.
![stylesheet_id_select](https://github.com/zathras/jovial_svg/assets/20762139/5fbd6120-5e1c-4ea7-959b-90146683ec4e)

**Comment by zathras** [comment]
Around now :-)

**Comment by Matthew-w56** [comment]
Wow, amazing!  Thanks!!!

**Comment by zathras** [comment]
Released in 1.1.21
