### ISSUE TITLE
Evaluate a generated SVG Icon

### ISSUE THREAD

**Issue by oravecz-jpmc** [zathras/jovial_svg#99]
There is no discussion group for this package, so please allow me to post this here for feedback.

I have an Icon generator tool that I point at a folder with a thousand SVG icons. I take the following steps.

1. Read each SVG file in as a string
2. String replace `RegExp(r'fill="#[0-9a-fA-F]{6}"')` with `fill="currentColor"` (our design tool does not output currentColor as a fill parameter)
3. Use `ScalableImage.fromSvgString()` to convert the SVG string to a `ScalableImage`
4.  Base64 encode the `si.toSIBytes()` to a String
5. Use mustache to generate an Icon component and embed the encoded `ScalableImage`

My mustache template will produce output like the following.

```dart
import 'dart:convert';

import 'package:flutter/widgets.dart';
import 'package:jovial_svg/jovial_svg.dart';

const _siEncoded = 'sLAeBwAA...MzM3AI8=';
final _siBytes = base64.decode(_siEncoded);
final _si = ScalableImage.fromSIBytes(_siBytes);

/*
 * Original SVG
 * <svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
 * <g clip-path="url(#clip0_126_18931)">
 * <path d="M4.7166 10.7169V9.43377C3.82911 ... 5.03738 4.30127Z" fill="currentColor"/>
 * </g>
 * <defs>
 * <clipPath id="clip0_126_18931">
 * <rect width="12" height="12" fill="white"/>
 * </clipPath>
 * </defs>
 * </svg>
 * 
*/
class BiotechOutlinedIcon extends StatelessWidget {
  const BiotechOutlinedIcon({
    super.key,
    this.width,
    this.height,
    this.alignment,
    this.background,
    this.clip,
    this.color,
  });

  final Alignment? alignment;
  final Color? background;
  final Color? color;
  final bool? clip;
  final double? width;
  final double? height;

  @override
  Widget build(BuildContext context) {
    final si = (color != null) ? _si.modifyCurrentColor(color!) : _si;

    return DecoratedBox(
      key: key,
      decoration: BoxDecoration(
        color: background,
      ),
      child: SizedBox(
        height: height ?? 24,
        width: width ?? 24,
        child: ScalableImageWidget(
          si: si,
          alignment: alignment ?? Alignment.center,
          clip: clip ?? true,
          fit: BoxFit.contain,
        ),
      ),
    );
  }
}

```

The reason I chose this approach is that we have thousands of icons in our catalog, and I did not want to treat the SVG files as assets. Assets are not tree-shaken when included in our applications, so even if the resulting native binary only uses a few icons, they pay the penalty of binding all of the asset files which increases the final binary by megabytes of unused assets.

There are issues with the way this package is distributed which makes writing a Dart CLI tool difficult. There is a package dependency on `dart:ui` which means this will not run as a Dart CLI. Instead, I have to run the generator as a Flutter test which allows me to still run "like" a CLI, and have `dart:ui` included. I think it would be much more convenient to package the encoding/decoding of the Jovial format so there is no dependency on the widget that displays it, or at least the `dart:ui` package.

I have a few questions

1. Is the widget as performant as I can make it? I may replace the nested `DecoratedBox`/`SizedBox` with a `Container` if the performance test shows a benefit.
2. Is there a better way to serialize the ScalableImage? `Utf8List` is available, but I didn't come up with a convenient way to export the Utf8List into a string that I can embed in my mustache template. I know there is some overhead induced by having to base64 decode the string, but I am assuming it is minimal compared to render time.

**Comment by zathras** [comment]
Is there a reasonable place to have a discussion group?  Generally speaking, I haven't seen discussion groups for Flutter packages, but I also haven't really looked!

Why aren't you just generating the binary file with `svg_to_si`?  You seem to have re-written the command line tool in a way that drags in dart:ui dependencies!  `svg_to_si` gives you the same thing as `toSiBytes` in a file; from there it's straightforward to write a simple command-line tool to read that file, a encode it however you want.

About performance, "it depends."  That's mostly a matter of standard optimization techniques.  Like, caching the pixmap rendering can make things a lot faster under the right circumstances; under the wrong circumstances it can add extra overhead.

**Comment by oravecz-jpmc** [comment]
This GitHub repository has a "Discussions" tab that you can enable. Here is [Riverpod's discussions](https://github.com/rrousselGit/riverpod/discussions) as a sample.

`svg_to_si` only outputs to a file, and `DataOutputSink` is not a class I can extend. I need to output to some type of encoding that I can package within the component, and not as an asset. If you wrote to a Sink interface, I could provide my own implementation backed by a StringBuffer or an in-memory sink.

**Comment by zathras** [comment]
Why would you want to extend `DataOutputSink`, given that its constructor already takes a `List<int>` where they bytes get sent?  I'm not sure why you think it can't be extended -- it's not final -- but that's moot anyway.  https://pub.dev/documentation/jovial_misc/latest/io_utils/DataOutputSink-class.html

Or, you could use the existing command-line too to send stuff to a temporary file.  This is part of your build process, right?  Making temporary files is probably the more normal thing to do in a build.  But if you want to save a tiny bit of launching overhead (and writing to a RAM disk) in your build, using `DataOutputSink` to write to a byte array in Dart is fine too.

**Comment by zathras** [comment]
Thanks for the tip about "discussions."  It turns out there's a checkbox that enables that down in the github settings.
